version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "1099:1099" # Standard RMI Port

  subscriber:
    build:
      context: .
      dockerfile: Dockerfile.subscriber
    depends_on:
      - server # Ensures server starts first!
